config/routes.rb
RailsWithAjax::Application.routes.draw do
  resources :pastebins

end

app/models/pastebin.rb
class Pastebin < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pastebins_controller.rb
class PastebinsController < ApplicationController
  def index
    @pastebins = Pastebin.all
  end

  def create
    pastebin = Pastebin.new(title: params[:title], text: params[:text])
    if pastebin.save
      data = {
        id: pastebin.id,
        title: pastebin.title,
        text: pastebin.text
      }
      render json: pastebin.to_json
    else
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pastebins_helper.rb
module PastebinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsWithAjax</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pastebins/index.html.erb
<h1>All Pastebins</h1>
<h2>Create new pastebins</h2>
<p>title : <br />
    <%= text_field_tag "pastebin[title]" %>
</p>
<p>text : <br />
    <%= text_area_tag "pastebin[text]" %>
</p>
<button type="submit" onclick="new_pastebin()">create pastebin</button>

<h2>Show all pastebins</h2>
<table id="pastebin_table">
    <tr>
        <td>ID</td>
        <td>TITLE</td>
        <td>TEXT</td>
    </tr>
    <% @pastebins.each do |pastebin| %>
        <tr>
            <td><%= pastebin.id %></td>
            <td><%= pastebin.title %></td>
            <td><%= pastebin.text %></td>
        </tr>
    <% end %>
</table>

<script type="text/javascript">
    function new_pastebin() {
        $.ajax({url: "<%= pastebins_path %>",
                type: "post",
                data: {title: $("#pastebin_title").val(),
                        text: $("#pastebin_text").val()
                        },

                success: function(pastebin) {
                    $("#pastebin_table").append("<tr><td>" + pastebin.id + "</td><td>" + pastebin.title + "</td><td>" + pastebin.text + "</td></tr>");
                }});
    }
</script>